Updating Cake, Cake.Recipe, Packages, and project structure.
cake-contrib/Cake.PinNuGetDependency pull request #23
Opened 2019-08-05 00:19 UTC by phillipsj

@gep13 is this what you were asking to be completed?

2019-08-05 05:07 UTC, glennawatson requested changes

2019-08-05 05:07 UTC, glennawatson commented on src/Cake.PinNuGetDependency/PinNuGetDependancyAliases.cs
> +        ///
Probably should give it a comment

2019-08-05 06:12 UTC, gep13 commented
@phillipsj essentially, yes.  This project is further along the lines than some of the others that I pointed you at, but the overhaul that you have provided here does bring it into line with some of the conventions that are going across other addins within the Cake Contrib Organisation.

If @glennawatson and others have no objections, it would be great to get this merged in.

2019-08-05 09:58 UTC, glennawatson commented
Apart from the comment it looks good to me.

2019-08-05 10:43 UTC, phillipsj commented
Nice catch.  I know what happened, I got distracted and didn't make it
back. I will fix it tonight and squash.

On Mon, Aug 5, 2019, 5:58 AM Glenn <notifications@github.com> wrote:

> Apart from the comment it looks good to me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cake-contrib/Cake.PinNuGetDependency/pull/23?email_source=notifications&email_token=AAL63BK7AKGBIEM52DCRCS3QC72VRA5CNFSM4IJGSM7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3RKJHI#issuecomment-518169757>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAL63BOKWPPVOUZIUP7UFODQC72VRANCNFSM4IJGSM7A>
> .
>

2019-08-24 18:57 UTC, gep13 commented
Relates to #24

2019-08-24 18:59 UTC, gep13 commented
@phillipsj @glennawatson I am going to get this merged, and fixed up.

2019-08-24 19:00 UTC, merged

2019-08-24 19:17 UTC, phillipsj commented
Thanks.  I have been so busy my list is too long and not enough time.

On Sat, Aug 24, 2019, 2:59 PM Gary Ewan Park <notifications@github.com>
wrote:

> @phillipsj <https://github.com/phillipsj> @glennawatson
> <https://github.com/glennawatson> I am going to get this merged, and
> fixed up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cake-contrib/Cake.PinNuGetDependency/pull/23?email_source=notifications&email_token=AAL63BICV5UKYMJED2SRZZTQGGAJXA5CNFSM4IJGSM7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5CFVWI#issuecomment-524573401>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAL63BJGANIQ76P7X2GOLLTQGGAJXANCNFSM4IJGSM7A>
> .
>

2019-08-24 19:21 UTC, gep13 commented
@phillipsj not a problem at all.  Working my way through my list, and this one was on it 😄